from __future__ import annotations

import ntpath
import posixpath
import re
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator


VideoLocalizationMediaExportKind = Literal["video", "audio", "subtitle"]
VideoLocalizationAudioTrackId = Literal[
    "original",
    "vocals",
    "background",
    "dub",
]
VideoLocalizationSubtitleTrackId = Literal["asr", "localized"]
VideoLocalizationLocalizedSubtitleVariant = Literal["localized", "dub"]
_CONTROL_CHARACTERS = re.compile(r"[\x00-\x1f\x7f-\x9f]")


class VideoLocalizationMediaExportRequest(BaseModel):
    """Versioned public input for one flattened media export."""

    model_config = ConfigDict(extra="forbid")

    schema_version: Literal["v1"] = "v1"
    kind: VideoLocalizationMediaExportKind
    audio_tracks: list[VideoLocalizationAudioTrackId] = Field(
        default_factory=list,
        max_length=4,
    )
    dub_lanes: list[int] = Field(default_factory=list, max_length=64)
    subtitle_tracks: list[VideoLocalizationSubtitleTrackId] = Field(
        default_factory=list,
        max_length=2,
    )
    localized_subtitle_variant: (
        VideoLocalizationLocalizedSubtitleVariant
    ) = "localized"
    video_size: Literal["source", "1080p", "720p"] = "source"
    video_quality: Literal["source", "high", "balanced", "compact"] = "source"
    audio_format: Literal["wav", "mp3"] = "wav"
    audio_bitrate_kbps: Literal["source", 128, 192, 256] = "source"

    @model_validator(mode="after")
    def validate_selection(self) -> "VideoLocalizationMediaExportRequest":
        self.audio_tracks = list(dict.fromkeys(self.audio_tracks))
        self.dub_lanes = sorted(
            {
                lane
                for lane in self.dub_lanes
                if isinstance(lane, int) and not isinstance(lane, bool) and lane >= 0
            }
        )
        self.subtitle_tracks = list(dict.fromkeys(self.subtitle_tracks))
        if self.kind == "audio" and not self.audio_tracks:
            raise ValueError("音频导出至少需要选择一个音频轨道")
        if self.kind == "subtitle" and not self.subtitle_tracks:
            raise ValueError("字幕导出至少需要选择一个字幕轨道")
        if "dub" not in self.audio_tracks:
            self.dub_lanes = []
        if self.kind == "audio":
            self.subtitle_tracks = []
            self.localized_subtitle_variant = "localized"
        elif self.kind == "subtitle":
            self.audio_tracks = []
            self.dub_lanes = []
            self.video_size = "source"
            self.video_quality = "source"
            self.audio_format = "wav"
            self.audio_bitrate_kbps = "source"
            if (
                set(self.subtitle_tracks) == {"asr", "localized"}
                and self.localized_subtitle_variant == "dub"
            ):
                raise ValueError("双语字幕只能使用本土化字幕轨")
            if self.subtitle_tracks == ["asr"]:
                self.localized_subtitle_variant = "localized"
        return self


class VideoLocalizationMediaExportCommandRequest(BaseModel):
    """Start one background export into an authorized destination."""

    model_config = ConfigDict(extra="forbid")

    schema_version: Literal["v1"] = "v1"
    destination_id: str = Field(
        min_length=16,
        max_length=128,
        pattern=r"^[A-Za-z0-9_-]+$",
    )
    render: VideoLocalizationMediaExportRequest
    output_filename: str = Field(min_length=1, max_length=255)

    @model_validator(mode="after")
    def validate_output_filename(
        self,
    ) -> "VideoLocalizationMediaExportCommandRequest":
        self.output_filename = validate_media_export_output_filename(
            self.output_filename,
            self.render,
        )
        return self


class VideoLocalizationMediaExportFilenamePreviewResponse(BaseModel):
    """Default basename generated by the single export naming policy."""

    model_config = ConfigDict(extra="forbid")

    schema_version: Literal["v1"] = "v1"
    output_filename: str = Field(min_length=1, max_length=255)


class VideoLocalizationExportDestinationRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")

    mode: Literal["default", "choose"] = "default"


class VideoLocalizationExportDestinationResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    status: Literal["selected", "cancelled"]
    destination_id: str | None = None
    display_path: str | None = None


def validate_media_export_output_filename(
    output_filename: str,
    request: VideoLocalizationMediaExportRequest,
) -> str:
    """Validate one user-visible export basename without accepting a path."""

    filename = str(output_filename)
    if not filename or filename != filename.strip():
        raise ValueError("导出文件名不能为空或包含首尾空白")
    if len(filename) > 255:
        raise ValueError("导出文件名不能超过 255 个字符")
    if (
        filename in {".", ".."}
        or posixpath.basename(filename) != filename
        or ntpath.basename(filename) != filename
        or "/" in filename
        or "\\" in filename
    ):
        raise ValueError("导出文件名只能是文件名，不能包含目录")
    if _CONTROL_CHARACTERS.search(filename):
        raise ValueError("导出文件名不能包含控制字符")
    expected_extension = {
        "video": ".mp4",
        "audio": f".{request.audio_format}",
        "subtitle": ".srt",
    }[request.kind]
    if ntpath.splitext(filename)[1] != expected_extension:
        raise ValueError(
            f"导出文件扩展名必须是 {expected_extension}"
        )
    return filename


__all__ = [
    "VideoLocalizationExportDestinationRequest",
    "VideoLocalizationExportDestinationResponse",
    "VideoLocalizationMediaExportCommandRequest",
    "VideoLocalizationMediaExportFilenamePreviewResponse",
    "VideoLocalizationMediaExportRequest",
    "validate_media_export_output_filename",
]
