from __future__ import annotations

from app.schemas.voice_studio import EngineDetail, EngineManifest, EngineState, EngineStatus, ParameterSchema
from app.services import confucius4_paths, doubao_client, mimo_client


EMOTION_OPTIONS = [
    {"label": "自然 calm", "value": "calm"},
    {"label": "高兴 happy", "value": "happy"},
    {"label": "悲伤 sad", "value": "sad"},
    {"label": "愤怒 angry", "value": "angry"},
    {"label": "恐惧 afraid", "value": "afraid"},
    {"label": "反感 disgusted", "value": "disgusted"},
    {"label": "低落 melancholic", "value": "melancholic"},
    {"label": "惊讶 surprised", "value": "surprised"},
]

EMOTIVOICE_PROMPTS = [
    {"label": "开心", "value": "开心"},
    {"label": "兴奋", "value": "兴奋"},
    {"label": "悲伤", "value": "悲伤"},
    {"label": "愤怒", "value": "愤怒"},
    {"label": "害怕", "value": "害怕"},
    {"label": "惊讶", "value": "惊讶"},
    {"label": "厌恶", "value": "厌恶"},
    {"label": "中立", "value": "中立"},
]

COSYVOICE_SPEAKERS = [
    {"label": "中文女", "value": "中文女"},
    {"label": "中文男", "value": "中文男"},
    {"label": "粤语女", "value": "粤语女"},
    {"label": "日语男", "value": "日语男"},
    {"label": "韩语女", "value": "韩语女"},
    {"label": "英文女", "value": "英文女"},
    {"label": "英文男", "value": "英文男"},
]

EMOTIVOICE_SPEAKERS = [
    {"label": "8051 Maria Kasper 女声 · 清晰舒缓", "value": "8051"},
    {"label": "11614 Sylviamb 女声 · 清脆旋律", "value": "11614"},
    {"label": "9017 John Van Stan 男声 · 浑厚共鸣", "value": "9017"},
    {"label": "6097 Phil Benson 男声 · 平滑醇厚", "value": "6097"},
    {"label": "6671 Tony Oliva 男声 · 有魅力", "value": "6671"},
    {"label": "6670 Mike Pelton 男声", "value": "6670"},
    {"label": "9136 Helen Taylor 女声", "value": "9136"},
    {"label": "11697 Celine Major 女声", "value": "11697"},
    {"label": "92 Cori Samuel 女声 · 活泼有能量", "value": "92"},
    {"label": "12787 LikeManyWaters 女声", "value": "12787"},
    {"label": "1006 Marta Kornowska 女声", "value": "1006"},
    {"label": "1018 JimmyLogan 男声", "value": "1018"},
]

OMNIVOICE_LANGUAGES = [
    {"label": "自动", "value": "auto"},
    {"label": "中文 zh", "value": "zh"},
    {"label": "英文 en", "value": "en"},
    {"label": "日语 ja", "value": "ja"},
    {"label": "韩语 ko", "value": "ko"},
    {"label": "法语 fr", "value": "fr"},
    {"label": "德语 de", "value": "de"},
    {"label": "西班牙语 es", "value": "es"},
]

CONFUCIUS4_LANGUAGES = [
    {"label": "中文 zh", "value": "zh"},
    {"label": "英文 en", "value": "en"},
    {"label": "越南语 vi", "value": "vi"},
    {"label": "日语 ja", "value": "ja"},
    {"label": "韩语 ko", "value": "ko"},
    {"label": "泰语 th", "value": "th"},
]
assert tuple(item["value"] for item in CONFUCIUS4_LANGUAGES) == confucius4_paths.SUPPORTED_LANGUAGE_CODES

QWEN3_TTS_SPEAKERS = [
    {"label": "Vivian · 中文/英文女声", "value": "Vivian"},
    {"label": "Serena · 中文/英文女声", "value": "Serena"},
    {"label": "Uncle_Fu · 中文男声", "value": "Uncle_Fu"},
    {"label": "Dylan · 中文男声", "value": "Dylan"},
    {"label": "Eric · 中文男声", "value": "Eric"},
    {"label": "Ryan · 英文男声", "value": "Ryan"},
    {"label": "Aiden · 英文男声", "value": "Aiden"},
    {"label": "Ono_Anna · 日文女声", "value": "Ono_Anna"},
    {"label": "Sohee · 韩文女声", "value": "Sohee"},
]

QWEN3_TTS_LANGUAGES = [
    {"label": "自动判断", "value": "auto"},
    {"label": "中文", "value": "chinese"},
    {"label": "英文", "value": "english"},
    {"label": "日文", "value": "japanese"},
    {"label": "韩文", "value": "korean"},
    {"label": "德文", "value": "german"},
    {"label": "意大利文", "value": "italian"},
    {"label": "葡萄牙文", "value": "portuguese"},
    {"label": "西班牙文", "value": "spanish"},
    {"label": "法文", "value": "french"},
    {"label": "俄文", "value": "russian"},
]




def common_params(v2: bool = False) -> list[ParameterSchema]:
    params = [
        ParameterSchema(key="speed", label="语速", type="slider", default=1.0, min=0.5, max=2.0, step=0.05, description="1.0 是正常；调大读得更快，调小读得更慢。建议先只在 0.8、1.0、1.2 附近试听。"),
        ParameterSchema(key="temperature", label="随机性 Temperature", type="slider", default=0.8 if v2 else 1.0, min=0.1, max=2.0, step=0.05, level="advanced" if v2 else None, description="控制每次读法的变化程度。调低更稳定；调高变化更多，但可能出现不自然停顿。没有明确需求时保持默认。"),
        ParameterSchema(key="top_p", label="采样范围 Top-P", type="slider", default=0.8, min=0, max=1, step=0.05, level="advanced", description="控制读法的保守程度。调低通常更稳，调高会增加变化；一般不需要单独调整。"),
        ParameterSchema(key="top_k", label="候选数量 Top-K", type="slider", default=30, min=1, max=100, step=1, level="advanced", description="控制模型可选择的读法数量。数值小通常更稳；数值大变化更多。除非在排查重复或读法单调，否则保持默认。"),
        ParameterSchema(key="max_text_tokens_per_segment", label="分段长度", type="slider", default=120, min=20, max=500, step=10, level="advanced", description="一段最多容纳多少文字。调小更容易在句子间分段，调大更连贯但长句出错时更难定位；长文建议保持默认并先看分句预览。"),
        ParameterSchema(key="interval_silence", label="段间停顿", type="slider", default=200, min=0, max=2000, step=50, level="advanced", description="两段文字之间额外留出的停顿。调大段落感更明显，调小会更紧凑。"),
    ]
    if v2:
        params.extend([
            ParameterSchema(
                key="emotion",
                label="情绪",
                type="select",
                default="",
                options=EMOTION_OPTIONS,
                capability="emotion_control",
                description="选择想要的整体情绪。高兴会更明亮有活力，悲伤更收敛低沉；留在“跟随参考音色”时最接近原参考声音的情绪。",
            ),
            ParameterSchema(key="emo_alpha", label="情绪强度", type="slider", default=0.6, min=0, max=1, step=0.05, capability="emotion_control", description="只在手动选了情绪后生效。调低更自然克制，调高表演感更强；太高可能显得夸张。"),
            ParameterSchema(key="max_mel_tokens", label="最长生成量", type="slider", default=1500, min=100, max=1815, step=50, level="advanced", description="单段最多允许生成多长的声音。长句被提前截断时再调大；数值越大等待越久，通常保持默认。"),
            ParameterSchema(key="repetition_penalty", label="重复抑制", type="slider", default=10.0, min=1.0, max=20.0, step=0.5, level="advanced", description="防止连续重复字词或音节。真的出现重复读时才小幅调高；过高会让读法变硬。"),
            ParameterSchema(key="diffusion_steps", label="声音细化步数", type="slider", default=25, min=5, max=60, step=1, level="advanced", description="每次生成用于细化声音的次数。调高可能更细腻但明显更慢，不保证一定更好；正式使用先保持默认。"),
            ParameterSchema(key="cfg_rate", label="参考贴合度", type="slider", default=0.7, min=0, max=1, step=0.05, level="advanced", description="控制生成有多努力贴近参考声音和情绪。调高更贴近但可能不自然，调低更自由；一般保持默认。"),
        ])
    return params


ENGINES: dict[str, EngineDetail] = {
    "indextts-v2": EngineDetail(
        manifest=EngineManifest(
            engine_id="indextts-v2",
            display_name="IndexTTS v2",
            provider="Index Team",
            version="2.0",
            description="Bilibili IndexTeam 工业级零样本 TTS，支持 8 种情绪控制和声音克隆",
            supported_languages=["zh", "en"],
            capabilities=["local_inference", "voice_clone", "emotion_control", "long_text", "pinyin_control"],
            sample_rate=22050,
            max_tokens=1815,
            default_use_case="中文/英文情绪化配音",
            parameter_schema=common_params(v2=True),
        ),
        state=EngineState(engine_id="indextts-v2", status=EngineStatus.stopped),
    ),
    "omnivoice": EngineDetail(
        manifest=EngineManifest(
            engine_id="omnivoice",
            display_name="OmniVoice",
            provider="k2-fsa",
            version="0.1.5",
            description="k2-fsa 出品，600+ 语言零样本声音克隆与声音设计",
            supported_languages=["auto", "zh", "en", "ja", "ko", "fr", "de", "es"],
            capabilities=["local_inference", "voice_clone", "voice_design", "multilingual", "nonverbal_tags", "pinyin_control"],
            sample_rate=24000,
            default_use_case="多语言克隆与声音设计",
            parameter_schema=[
                ParameterSchema(key="language", label="语言", type="select", default="auto", options=OMNIVOICE_LANGUAGES, description="语言提示。自动可混语，手动选择通常更稳。"),
                ParameterSchema(key="emotion_text", label="声音设计标签", type="textarea", default="", capability="voice_design", description="没有选参考音色时，用“性别、年龄、音调、耳语”等官方标签组合决定声音类型，例如“女，青年，中音调”。它不是聊天式描述；填写“温柔、自然、略慢”等自由句子会被模型拒绝。"),
                ParameterSchema(key="speed", label="语速", type="slider", default=1.0, min=0.5, max=2.0, step=0.05, description="1.0 是正常；调大读得更快、音频更短，调小读得更慢、音频更长。本项目会在生成后用不变调方式调整时长；仍建议先用短句试听。"),
                ParameterSchema(key="diffusion_steps", label="扩散步数 Num Step", type="slider", default=32, min=4, max=64, step=1, level="advanced", description="OmniVoice 生成步数。越高通常越细致但更慢。"),
                ParameterSchema(key="guidance_scale", label="引导强度 Guidance", type="slider", default=2.0, min=0.0, max=5.0, step=0.1, level="advanced", description="控制生成结果贴合文本、音色或声音描述的力度。0 表示关闭这层额外引导；数值越高通常越贴合，默认 2.0。"),
                ParameterSchema(key="duration", label="固定时长 s", type="number", default=0, min=0, max=120, step=0.5, level="advanced", description="可选。0 表示自动估算；填秒数会在完整生成后拉伸/压缩到目标时长。目标时长和文字长度不匹配时，语速和自然度可能受影响。"),
                ParameterSchema(key="audio_chunk_duration", label="长文本分段目标 s", type="number", default=15.0, min=1.0, max=120.0, step=1.0, level="advanced", description="OmniVoice 官方长文本切分目标时长。默认每段约 15 秒。"),
                ParameterSchema(key="audio_chunk_threshold", label="长文本切分阈值 s", type="number", default=30.0, min=1.0, max=600.0, step=1.0, level="advanced", description="预计音频超过该时长时启用 OmniVoice 内置长文本切分。官方默认 30 秒。"),
                ParameterSchema(key="t_shift", label="扩散时间偏移 T-Shift", type="number", default=0.1, min=0.0, max=1.0, step=0.01, level="developer", description="OmniVoice 官方扩散时间轴的微调项。只会改变内部生成轨迹，不是语速；没有做模型调试时保持 0.1。"),
                ParameterSchema(key="layer_penalty_factor", label="层级惩罚 Layer Penalty", type="number", default=5.0, min=0.0, max=20.0, step=0.1, level="developer", description="OmniVoice 内部层级选择的调试项。它不直接对应音量或情绪，通常保持默认 5.0。"),
                ParameterSchema(key="position_temperature", label="位置随机度 Position Temperature", type="number", default=5.0, min=0.0, max=20.0, step=0.1, level="developer", description="控制 OmniVoice 内部位置选择的随机程度。只用于模型调试；日常配音请保持默认 5.0。"),
                ParameterSchema(key="class_temperature", label="类别随机度 Class Temperature", type="number", default=0.0, min=0.0, max=20.0, step=0.1, level="developer", description="控制 OmniVoice 内部类别选择的随机程度。0 是官方默认；除非在复现实验，否则不要改。"),
                ParameterSchema(key="denoise", label="扩散降噪", type="toggle", default=True, level="developer", description="是否执行 OmniVoice 官方的扩散降噪收尾。关闭后更适合排查模型过程，正常生成请保持开启。"),
                ParameterSchema(key="preprocess_prompt", label="预处理声音提示", type="toggle", default=True, level="developer", description="是否先整理参考音频或声音描述再生成。正常生成保持开启；关闭只用于对照排查。"),
                ParameterSchema(key="postprocess_output", label="后处理生成音频", type="toggle", default=True, level="developer", description="是否执行 OmniVoice 官方输出后处理。关闭只用于定位问题，正常成品请保持开启。"),
            ],
        ),
        state=EngineState(engine_id="omnivoice", status=EngineStatus.stopped),
    ),
    "emotivoice": EngineDetail(
        manifest=EngineManifest(
            engine_id="emotivoice",
            display_name="EmotiVoice",
            provider="NetEase Youdao",
            version="open-source",
            description="网易有道开源中英双语情感 TTS，2000+ 官方预置声音，用提示词控制情绪",
            supported_languages=["zh", "en"],
            capabilities=["local_inference", "preset_voice", "emotion_control"],
            sample_rate=16000,
            default_use_case="中文角色感、情绪短句和音色预设试听",
            parameter_schema=[
                ParameterSchema(
                    key="speaker_id",
                    label="说话人",
                    type="select",
                    default="8051",
                    options=EMOTIVOICE_SPEAKERS,
                    required=True,
                    capability="preset_voice",
                    description="选择 EmotiVoice 自带的官方预置声音。换这里就会换音色；它不是“上传一段音频立刻复刻”的功能。",
                ),
                ParameterSchema(
                    key="prompt",
                    label="演绎提示",
                    type="text",
                    default="开心",
                    options=EMOTIVOICE_PROMPTS,
                    capability="emotion_control",
                    description="决定这一句怎么演绎。可直接选常用情绪，也可以写自己的提示，例如“克制、略带疲惫”。开心通常更明亮有活力，悲伤更收敛；先用短句试听最稳。",
                ),
            ],
        ),
        state=EngineState(engine_id="emotivoice", status=EngineStatus.stopped),
    ),
    "confucius4-mlx-int8": EngineDetail(
        manifest=EngineManifest(
            engine_id="confucius4-mlx-int8",
            display_name="Confucius4-TTS MLX int8",
            provider="NetEase Youdao / Hert4 MLX",
            version="int8 MLX",
            description="网易有道子曰4 TTS 的 Apple Silicon MLX int8 版本，支持当前本机运行时已验证的 6 种语言零样本声音克隆和情绪迁移",
            supported_languages=[item["value"] for item in CONFUCIUS4_LANGUAGES],
            capabilities=["local_inference", "voice_clone", "zero_shot", "emotion_transfer", "cross_lingual", "multilingual"],
            sample_rate=22050,
            default_use_case="使用音色库或自定义参考音频做跨语种情绪迁移",
            privacy_level="local_only_research",
            parameter_schema=[
                ParameterSchema(
                    key="language",
                    label="目标语言",
                    type="select",
                    default="zh",
                    options=CONFUCIUS4_LANGUAGES,
                    description="告诉模型正文要按哪种语言发音。当前本机运行时只支持这里列出的 6 种语言；手动选择与正文一致的语言通常更稳。",
                ),
                ParameterSchema(key="temperature", label="随机性 Temperature", type="slider", default=0.8, min=0.1, max=1.5, step=0.05, level="advanced", description="控制每次读法的变化。调低更稳定，调高变化更多但可能不自然；本地 MLX 默认 0.8。"),
                ParameterSchema(key="top_p", label="采样范围 Top-P", type="slider", default=0.8, min=0.01, max=1.0, step=0.01, level="advanced", description="控制读法的保守程度。调低会更稳，调高会增加变化；默认 0.8 通常够用。"),
                ParameterSchema(key="top_k", label="候选数量 Top-K", type="slider", default=30, min=1, max=100, step=1, level="advanced", description="控制模型可选择的读法数量。小一点更稳，大一点变化更多；没有明确问题时保持默认。"),
                ParameterSchema(key="repetition_penalty", label="重复抑制", type="slider", default=10.0, min=1.0, max=20.0, step=0.5, level="advanced", description="防止重复发音或重复片段。真的有重复读时再小幅调高，过高会让声音不自然。"),
                ParameterSchema(key="diffusion_steps", label="声音细化步数", type="slider", default=25, min=1, max=60, step=1, level="advanced", description="生成时细化声音的次数。调高通常更慢，未必每次都更好；本地 MLX 默认 25。"),
                ParameterSchema(key="cfg_rate", label="参考贴合度", type="slider", default=0.7, min=0.0, max=1.0, step=0.05, level="advanced", description="控制声音有多努力贴近参考音色和文本。调高更贴近但可能僵硬，调低更自由；默认 0.7。"),
                ParameterSchema(key="seed", label="随机种子", type="number", default=0, min=0, max=2147483647, step=1, level="developer", description="让同一组测试尽量可重复。相同种子更容易得到相近结果；只在对比参数时需要改。"),
            ],
        ),
        state=EngineState(engine_id="confucius4-mlx-int8", status=EngineStatus.stopped),
    ),
    "qwen3-tts-mlx-0.6b": EngineDetail(
        manifest=EngineManifest(
            engine_id="qwen3-tts-mlx-0.6b",
            display_name="Qwen3-TTS MLX 0.6B",
            provider="Qwen / MLX Community",
            version="0.6B 8-bit PoC",
            description="在 Apple Silicon 上运行的 Qwen3-TTS MLX 实验引擎。预置音色和参考音色克隆来自本地运行链路；声音设计使用社区转换模型，适合短句试音后再决定是否用于正式成片。",
            supported_languages=[item["value"] for item in QWEN3_TTS_LANGUAGES],
            capabilities=["local_inference", "preset_voice", "voice_design", "voice_clone", "multilingual", "natural_language_control"],
            sample_rate=24000,
            max_tokens=1200,
            default_use_case="本地短句口播、预置音色试听、声音设计和声音克隆 PoC",
            privacy_level="local_only_research",
            parameter_schema=[
                ParameterSchema(
                    key="language",
                    label="目标语言",
                    type="select",
                    default="chinese",
                    options=QWEN3_TTS_LANGUAGES,
                    description="选择正文语言，让模型按对应语言发音。自动判断适合混合文本；语言明确时手动选择通常更稳。",
                ),
                ParameterSchema(
                    key="speaker_id",
                    label="预置声音",
                    type="select",
                    default="Vivian",
                    options=QWEN3_TTS_SPEAKERS,
                    capability="preset_voice",
                    description="未选择参考音色时使用的 Qwen3 预置声音。",
                ),
                ParameterSchema(
                    key="style_instruction",
                    label="演绎指令",
                    type="textarea",
                    default="",
                    capability="natural_language_control",
                    description="只在使用 Qwen3 预置声音时生效。用一句话告诉它这次要怎么说，例如“温柔、耐心，像在讲解课程”。留空时使用 Normal tone；选择参考音色或填写声音描述后，这项不会参与生成。",
                ),
                ParameterSchema(
                    key="voice_design_prompt",
                    label="声音描述",
                    type="textarea",
                    default="",
                    capability="voice_design",
                    description="描述你想要的声音本身，例如“年轻中文女声，声线温暖，吐字清晰”。填写后会走本地 MLX 社区转换的声音设计路线；效果适合先用短句试听，不等同于 Qwen 官方 0.6B 的已发布能力。",
                ),
                ParameterSchema(key="speed", label="语速", type="slider", default=1.0, min=0.5, max=2.0, step=0.05, description="1.0 是正常；调大后整段会更短、读得更快，调小后会更长、读得更慢。当前 MLX 版会在生成后用不变调方式调整时长；长句仍应试听确认。"),
                ParameterSchema(key="temperature", label="随机性 Temperature", type="slider", default=0.7, min=0.1, max=2.0, step=0.05, level="advanced", description="本地 MLX 的随机性设置。调低时同一句更稳定、每次更像；调高时读法变化更多，但也更容易出现不自然的停顿。"),
                ParameterSchema(key="top_p", label="采样范围 Top-P", type="slider", default=0.9, min=0.01, max=1.0, step=0.01, level="advanced", description="本地 MLX 的候选范围设置。调低会让读法更保守稳定；调高会增加变化。一般保持默认即可。"),
                ParameterSchema(key="top_k", label="候选数量 Top-K", type="number", default=50, min=1, max=200, step=1, level="advanced", description="本地 MLX 每一步可参考的读法数量。数值小通常更稳，数值大可能更多变化；没有明确问题时保持默认。"),
                ParameterSchema(key="repetition_penalty", label="重复抑制", type="number", default=1.1, min=1.0, max=3.0, step=0.05, level="advanced", description="本地 MLX 防止连续重复字词或音节的力度。出现重复读时可小幅调高；太高会让语句变得生硬。"),
                ParameterSchema(key="max_tokens", label="最长生成量", type="number", default=1200, min=100, max=4096, step=50, level="advanced", description="本地 MLX 单次允许生成的最大长度。文本很长却被截断时再调大；数值越大，等待和失控风险也会增加。"),
            ],
        ),
        state=EngineState(engine_id="qwen3-tts-mlx-0.6b", status=EngineStatus.stopped),
    ),
    "f5-tts": EngineDetail(
        manifest=EngineManifest(
            engine_id="f5-tts",
            display_name="F5-TTS",
            provider="SWivid",
            version="v1 Base",
            description="基于 Flow Matching + DiT 的非自回归零样本 TTS，5 秒参考音频即可克隆",
            supported_languages=["zh", "en"],
            capabilities=["local_inference", "voice_clone", "multilingual"],
            sample_rate=24000,
            default_use_case="已授权参考音频的音色迁移和中英文生成研究",
            privacy_level="local_only_noncommercial_model",
            parameter_schema=[
                ParameterSchema(key="speed", label="语速", type="slider", default=1.0, min=0.5, max=2.0, step=0.05, description="1.0 是正常；调大读得更快，调小读得更慢。先用短句试听，过快可能牺牲自然停顿。"),
                ParameterSchema(key="nfe_step", label="声音细化步数", type="slider", default=32, min=4, max=64, step=1, level="advanced", description="生成时细化声音的次数。调高通常更慢，可能更细腻但不保证一定更好；默认 32 适合大多数情况。"),
                ParameterSchema(key="cfg_strength", label="参考贴合度", type="slider", default=2.0, min=0.1, max=5.0, step=0.1, level="advanced", description="控制生成有多努力贴近参考音色和文字。调高更贴近但可能生硬，调低更自然但可能不像参考声音；通常保持默认。"),
                ParameterSchema(key="target_rms", label="低音量参考补偿阈值", type="slider", default=0.1, min=0.01, max=0.5, step=0.01, level="developer", description="只在参考音频本身特别小声时，帮助模型先更稳定地听清参考声音；它不会把最终成品调得更响或更轻。参考音量正常时保持默认。"),
                ParameterSchema(key="cross_fade_duration", label="分段衔接", type="slider", default=0.15, min=0, max=1, step=0.05, level="advanced", description="长文本分段连接时的重叠时长。调大衔接更平滑，太大可能让相邻字词黏在一起；短句一般不用改。"),
                ParameterSchema(key="sway_sampling_coef", label="采样摆动 Sway", type="slider", default=-1.0, min=-1.0, max=1.0, step=0.1, level="developer", description="只用于微调同一段声音的采样轨迹，不是语速。-1 是官方默认，0 表示不使用这项修正；正负值都会改变细节走向，通常不要改。"),
                ParameterSchema(key="fix_duration", label="单块总时长 s", type="number", default=0.0, min=0.0, max=30.0, step=0.1, level="developer", description="可选。0 表示自动估算；填写后只会尝试限定“参考音频加当前生成块”的总时长，最长 30 秒。长文本会分块处理，因此不能保证整段成品正好等于这个时长。"),
                ParameterSchema(key="remove_silence", label="移除静音", type="toggle", default=False, level="advanced", description="自动删掉明显的空白停顿。适合素材剪辑；想保留自然呼吸、停顿和情绪节奏时不要开。"),
                ParameterSchema(key="seed", label="随机种子", type="number", default=None, min=0, max=2147483647, step=1, level="developer", description="填同一个整数后，可在其他参数和参考音频都不变时更容易复现同一版结果。留空让模型每次自行随机；它不保证跨模型版本完全一致。"),
            ],
        ),
        state=EngineState(engine_id="f5-tts", status=EngineStatus.stopped),
    ),
    "cosyvoice-sft": EngineDetail(
        manifest=EngineManifest(
            engine_id="cosyvoice-sft",
            display_name="CosyVoice SFT",
            provider="FunAudioLLM",
            version="300M-SFT",
            description="阿里巴巴 FunAudioLLM 多语种 TTS，官方 SFT 预置音色，支持中粤日韩英",
            supported_languages=["zh", "yue", "ja", "ko", "en"],
            capabilities=["local_inference", "preset_voice", "multilingual"],
            sample_rate=22050,
            default_use_case="高质量官方预置音色口播和多语种试听",
            parameter_schema=[
                ParameterSchema(
                    key="speaker_id",
                    label="预置音色",
                    type="select",
                    default="中文女",
                    options=COSYVOICE_SPEAKERS,
                    required=True,
                    capability="preset_voice",
                    description="选择 CosyVoice 自带的预置声音。它不是上传参考音频复刻；换选项即可直接换官方音色。",
                ),
                ParameterSchema(key="speed", label="语速", type="slider", default=1.0, min=0.5, max=2.0, step=0.05, description="1.0 是正常；调大读得更快，调小读得更慢。建议先在 0.8、1.0、1.3 附近试听。"),
            ],
        ),
        state=EngineState(engine_id="cosyvoice-sft", status=EngineStatus.stopped),
    ),
    "cosyvoice-zero-shot": EngineDetail(
        manifest=EngineManifest(
            engine_id="cosyvoice-zero-shot",
            display_name="CosyVoice Zero-Shot",
            provider="FunAudioLLM",
            version="300M",
            description="使用官方 CosyVoice-300M 参考音频和准确台词做零样本声音克隆。未安装该模型时会明确显示不可用，不会用 SFT 模型冒充。",
            supported_languages=["zh", "en", "yue", "ja", "ko"],
            capabilities=["local_inference", "voice_clone", "multilingual"],
            sample_rate=22050,
            default_use_case="使用已授权参考音频做官方 Zero-Shot 试音；需要先安装 CosyVoice-300M",
            parameter_schema=[
                ParameterSchema(key="speed", label="语速", type="slider", default=1.0, min=0.5, max=2.0, step=0.05, description="1.0 是正常；调大读得更快，调小读得更慢。它会保持参考音色路线，建议先用短句确认自然度。"),
            ],
        ),
        state=EngineState(engine_id="cosyvoice-zero-shot", status=EngineStatus.stopped),
    ),
    "mimo-v2.5-tts-preset": EngineDetail(
        manifest=EngineManifest(
            engine_id="mimo-v2.5-tts-preset",
            display_name="MiMo V2.5 TTS Preset",
            engine_type="cloud",
            provider="Xiaomi MiMo",
            version="2.5",
            description="小米云端精品音色合成，支持自然语言风格控制和唱歌标签",
            supported_languages=["zh", "en"],
            capabilities=["cloud_api", "preset_voice", "natural_language_control", "audio_tags", "singing"],
            supported_output_formats=["wav"],
            default_use_case="云端中文/英文口播、唱歌和官方预置音色快速合成",
            privacy_level="cloud_required",
            parameter_schema=[
                ParameterSchema(
                    key="mimo_voice",
                    label="MiMo 官方音色",
                    type="select",
                    default="mimo_default",
                    options=[{"label": item["label"], "value": item["voice_id"]} for item in mimo_client.MIMO_PRESET_VOICES],
                    required=True,
                    capability="preset_voice",
                    description="选择 MiMo 云端自带的声音。这里不需要上传参考音频；换一个选项就会换成对应官方音色。",
                ),
                ParameterSchema(key="style_instruction", label="风格指令", type="textarea", default="", capability="natural_language_control", description="用自然语言告诉它要怎么说，例如“语速稍慢，像朋友耐心讲解，重点前短暂停顿”。它会影响节奏、情绪和说话感觉；MiMo 没有单独的数值语速滑块，可在这里表达语速偏好。"),
            ],
        ),
        state=EngineState(engine_id="mimo-v2.5-tts-preset", status=EngineStatus.stopped),
    ),
    "mimo-v2.5-tts-voicedesign": EngineDetail(
        manifest=EngineManifest(
            engine_id="mimo-v2.5-tts-voicedesign",
            display_name="MiMo V2.5 TTS VoiceDesign",
            engine_type="cloud",
            provider="Xiaomi MiMo",
            version="2.5",
            description="小米云端音色设计，用一段文字描述即可生成全新声音",
            supported_languages=["zh", "en"],
            capabilities=["cloud_api", "voice_design", "natural_language_control"],
            supported_output_formats=["wav"],
            default_use_case="探索角色音色、一次性生成定制声音样本",
            privacy_level="cloud_required",
            parameter_schema=[
                ParameterSchema(key="voice_design_prompt", label="音色描述", type="textarea", default="", required=True, capability="voice_design", description="描述想要的声音本身，例如年龄、性别、音色质感、情绪和说话节奏。它会据此临时设计声音，不是复刻某段上传音频。"),
                ParameterSchema(
                    key="optimize_text_preview",
                    label="润色播报文本",
                    type="toggle",
                    default=False,
                    level="advanced",
                    capability="voice_design",
                    description="让 MiMo 先把要播的文字整理得更像口播稿。适合草稿试音；如果正文必须逐字不变，例如配音、字幕对齐或合同文案，请关闭。",
                ),
            ],
        ),
        state=EngineState(engine_id="mimo-v2.5-tts-voicedesign", status=EngineStatus.stopped),
    ),
    "mimo-v2.5-tts-voiceclone": EngineDetail(
        manifest=EngineManifest(
            engine_id="mimo-v2.5-tts-voiceclone",
            display_name="MiMo V2.5 TTS VoiceClone",
            engine_type="cloud",
            provider="Xiaomi MiMo",
            version="2.5",
            description="小米云端音色复刻，上传参考音频即可零样本克隆任意说话人",
            supported_languages=["zh", "en"],
            capabilities=["cloud_api", "voice_clone", "natural_language_control", "audio_tags"],
            supported_output_formats=["wav"],
            default_use_case="使用已授权的本地参考音色做云端复刻合成",
            privacy_level="cloud_required",
            parameter_schema=[
                ParameterSchema(key="style_instruction", label="风格指令", type="textarea", default="", capability="natural_language_control", description="在保持所选参考音色的前提下，描述这次要怎么说，例如“语速稍慢、像讲故事、句尾轻收”。参考声音和文字会上传到 MiMo 云端。"),
            ],
        ),
        state=EngineState(engine_id="mimo-v2.5-tts-voiceclone", status=EngineStatus.stopped),
    ),
    "mimo-v2.5-asr": EngineDetail(
        manifest=EngineManifest(
            engine_id="mimo-v2.5-asr",
            display_name="MiMo V2.5 ASR",
            engine_type="cloud",
            provider="Xiaomi MiMo",
            version="2.5",
            description="小米云端语音识别，支持中英文音频转写",
            supported_languages=["auto", "zh", "en"],
            capabilities=["cloud_api", "speech_recognition", "transcription"],
            default_use_case="会议、录音和素材音频转文字",
            privacy_level="cloud_required",
            parameter_schema=[
                ParameterSchema(key="language", label="识别语言", type="select", default="auto", options=[{"label": x, "value": x} for x in ["auto", "zh", "en"]], description="选择识别语言，auto 自动检测"),
            ],
        ),
        state=EngineState(engine_id="mimo-v2.5-asr", status=EngineStatus.stopped),
    ),
    "doubao-tts-preset": EngineDetail(
        manifest=EngineManifest(
            engine_id="doubao-tts-preset",
            display_name="豆包语音 TTS 2.0",
            engine_type="cloud",
            provider="Volcengine / Doubao",
            version="seed-tts-2.0",
            description="火山引擎豆包语音合成模型 2.0，使用官方预置音色进行短文本云端合成",
            supported_languages=["auto", *doubao_client.DOUBAO_TTS_EXPLICIT_LANGUAGES],
            capabilities=["cloud_api", "preset_voice", "natural_language_control"],
            sample_rate=doubao_client.DEFAULT_TTS_SAMPLE_RATE,
            supported_output_formats=["wav", "mp3", "pcm", "ogg_opus"],
            default_use_case="中文短句口播、视频旁白和官方预置音色试听",
            privacy_level="cloud_required",
            parameter_schema=[
                ParameterSchema(
                    key="speaker_id",
                    label="豆包官方音色",
                    type="select",
                    default="zh_female_vv_uranus_bigtts",
                    options=[{"label": item["label"], "value": item["voice_id"]} for item in doubao_client.DOUBAO_TTS_PRESET_SPEAKERS],
                    required=True,
                    capability="preset_voice",
                    description="选择豆包官方自带的声音。换一个选项就会换成对应音色；点开音色库可以搜索和试听，不需要上传参考音频。",
                ),
                ParameterSchema(
                    key="language",
                    label="指定朗读语言",
                    type="select",
                    default="auto",
                    level="advanced",
                    options=[
                        {"label": "自动（让模型按文本和音色判断）", "value": "auto"},
                        *[
                            {"label": label, "value": code}
                            for code, label in doubao_client.DOUBAO_TTS_EXPLICIT_LANGUAGES.items()
                        ],
                    ],
                    description="默认自动判断。只有中英混排读错、或你确定文本只该读一种语言时再指定；一旦指定，其他语言内容可能被跳过或让请求失败。",
                ),
                ParameterSchema(key="speed", label="语速", type="slider", default=1.0, min=0.5, max=2.0, step=0.05, description="1.0 是正常；调大读得更快，调小读得更慢。建议先在 0.8、1.0、1.2 附近试听，过快会让停顿更紧。"),
                ParameterSchema(key="loudness_rate", label="音量", type="slider", default=0, min=-50, max=100, step=5, level="advanced", description="整体提高或降低成品音量。0 保持原样；往右更响，往左更轻。它不会修复爆音或底噪，混音前建议保持默认。"),
                ParameterSchema(key="pitch_rate", label="音调", type="slider", default=0, min=-12, max=12, step=1, level="advanced", description="整体抬高或压低声音的高低。0 不变；调高更尖亮，调低更厚沉。改得太多会显得不自然。"),
                ParameterSchema(key="sample_rate", label="采样率", type="select", default=doubao_client.DEFAULT_TTS_SAMPLE_RATE, level="advanced", options=[{"label": f"{rate / 1000:g} kHz", "value": rate} for rate in [8000, 16000, 22050, 24000, 32000, 44100, 48000]], description="决定输出文件保留多少声音细节。数值高通常更清晰、文件更大；48 kHz 适合视频和后期，日常试听可用 24 kHz。"),
                ParameterSchema(key="bit_rate", label="MP3 码率", type="select", default=doubao_client.DEFAULT_TTS_BIT_RATE, level="advanced", options=[{"label": f"{rate // 1000} kbps", "value": rate} for rate in [64000, 96000, 128000, 160000]], description="只在导出 MP3 时影响压缩质量。数值高更接近原声、文件也更大；160 kbps 是当前高质量默认。"),
                ParameterSchema(key="enable_subtitle", label="返回字级时间戳", type="toggle", default=False, level="advanced", description="生成时一并返回每个字的大致出现时间。后面要做字幕、口型或画面对齐时再开启；只想试听时不用开。"),
                ParameterSchema(key="silence_duration", label="结尾静音", type="number", default=0, min=0, max=30000, step=100, level="advanced", description="在整段声音结尾额外留出空白时间。0 不添加；需要接片尾音乐、转场或下一段画面时再加，单位是毫秒。"),
                ParameterSchema(key="aigc_watermark", label="AIGC 声音标识", type="toggle", default=False, level="advanced", description="会在音频结尾加入一小段可识别的 AI 生成节奏标记，方便平台或后续流程识别来源。需要合规标记时开启；纯内部试听或不想改变结尾听感时可关闭。"),
                ParameterSchema(key="max_length_to_filter_parenthesis", label="不朗读圆括号内容", type="toggle", default=False, level="advanced", description="脚本里写（人物备注、停顿说明）时，开启后圆括号里的说明不会被念出来；普通正文没有这类备注时不用开。"),
                ParameterSchema(key="disable_markdown_filter", label="过滤 Markdown 排版标记", type="toggle", default=False, level="advanced", description="开启后会尽量去掉 **粗体**、链接等常见 Markdown 符号再朗读，避免读出星号等标记。复杂排版未必都能自动清干净，正式生成前仍建议先整理文本。"),
                ParameterSchema(key="latex_parser_mode", label="公式朗读", type="select", default="off", level="advanced", options=[{"label": "关闭", "value": "off"}, {"label": "基础公式朗读", "value": "basic"}, {"label": "增强公式朗读（较慢）", "value": "enhanced"}], description="把 LaTeX 数学写法按公式念出来。普通口播不需要；增强模式更适合复杂公式，但生成会更慢。"),
                ParameterSchema(key="aigc_metadata_enable", label="写入隐藏来源信息", type="toggle", default=False, level="advanced", description="把制作方和传播方等追溯信息写进成品，不会影响正常试听，也不会被朗读。需要平台或内部追溯时再开启。"),
                ParameterSchema(key="content_producer", label="内容制作方", type="text", default="", level="advanced", description="填写制作这段音频的团队、账号或公司名称。它只会写入隐藏来源信息，不会被念出来。"),
                ParameterSchema(key="produce_id", label="制作编号", type="text", default="", level="advanced", description="填写项目编号或内部追踪号。它只用于后续追溯，不会改变声音。"),
                ParameterSchema(key="content_propagator", label="内容传播方", type="text", default="", level="advanced", description="填写准备发布或传播这段音频的账号、团队或平台主体。它只写入隐藏来源信息。"),
                ParameterSchema(key="propagate_id", label="传播编号", type="text", default="", level="advanced", description="填写传播侧的内部编号或账号标识。没有自己的追溯规则时可以留空。"),
                ParameterSchema(
                    key="style_instruction",
                    label="语音指令",
                    type="textarea",
                    default="",
                    capability="natural_language_control",
                    description=(
                        "填写一句“这次要怎么说”的要求，例如“语速稍慢，像朋友耐心讲解，重点前短暂停顿”。它会影响语气、情绪、节奏和停顿；留空时用音色的自然读法。\n"
                        "示例：语速慢一点，语气更惊讶，句尾带一点感叹。\n"
                        "请把演绎要求写在本框，并先用短句试听；正文中的方括号会按普通文本处理。"
                    ),
                ),
            ],
        ),
        state=EngineState(engine_id="doubao-tts-preset", status=EngineStatus.stopped),
    ),
    "doubao-tts-voiceclone": EngineDetail(
        manifest=EngineManifest(
            engine_id="doubao-tts-voiceclone",
            display_name="豆包语音 TTS 2.0 · 声音复刻",
            engine_type="cloud",
            provider="Volcengine / Doubao",
            version="seed-icl-2.0",
            description="火山引擎豆包声音复刻 2.0，使用已训练成功的云端 speaker_id 合成新文本",
            supported_languages=["zh", "en"],
            capabilities=["cloud_api", "voice_clone"],
            sample_rate=doubao_client.DEFAULT_TTS_SAMPLE_RATE,
            supported_output_formats=["wav", "mp3", "pcm", "ogg_opus"],
            default_use_case="使用音色库中已训练成功的豆包云端复刻音色做中英文口播",
            privacy_level="cloud_required",
            parameter_schema=[
                ParameterSchema(key="speed", label="语速", type="slider", default=1.0, min=0.5, max=2.0, step=0.05, description="1.0 是正常；调大读得更快，调小读得更慢。建议先在 0.8、1.0、1.2 附近试听，过快会让停顿更紧。"),
                ParameterSchema(key="loudness_rate", label="音量", type="slider", default=0, min=-50, max=100, step=5, level="advanced", description="整体提高或降低成品音量。0 保持原样；往右更响，往左更轻。它不会修复爆音或底噪，混音前建议保持默认。"),
                ParameterSchema(key="pitch_rate", label="音调", type="slider", default=0, min=-12, max=12, step=1, level="advanced", description="整体抬高或压低声音的高低。0 不变；调高更尖亮，调低更厚沉。改得太多会显得不自然。"),
                ParameterSchema(key="sample_rate", label="采样率", type="select", default=doubao_client.DEFAULT_TTS_SAMPLE_RATE, level="advanced", options=[{"label": f"{rate / 1000:g} kHz", "value": rate} for rate in [8000, 16000, 22050, 24000, 32000, 44100, 48000]], description="决定输出文件保留多少声音细节。数值高通常更清晰、文件更大；48 kHz 适合视频和后期，日常试听可用 24 kHz。"),
                ParameterSchema(key="bit_rate", label="MP3 码率", type="select", default=doubao_client.DEFAULT_TTS_BIT_RATE, level="advanced", options=[{"label": f"{rate // 1000} kbps", "value": rate} for rate in [64000, 96000, 128000, 160000]], description="只在导出 MP3 时影响压缩质量。数值高更接近原声、文件也更大；160 kbps 是当前高质量默认。"),
                ParameterSchema(key="enable_subtitle", label="返回字级时间戳", type="toggle", default=False, level="advanced", description="生成时一并返回每个字的大致出现时间。后面要做字幕、口型或画面对齐时再开启；只想试听时不用开。"),
                ParameterSchema(key="silence_duration", label="结尾静音", type="number", default=0, min=0, max=30000, step=100, level="advanced", description="在整段声音结尾额外留出空白时间。0 不添加；需要接片尾音乐、转场或下一段画面时再加，单位是毫秒。"),
                ParameterSchema(key="aigc_watermark", label="AIGC 声音标识", type="toggle", default=False, level="advanced", description="会在音频结尾加入一小段可识别的 AI 生成节奏标记，方便平台或后续流程识别来源。需要合规标记时开启；纯内部试听或不想改变结尾听感时可关闭。"),
                ParameterSchema(key="max_length_to_filter_parenthesis", label="不朗读圆括号内容", type="toggle", default=False, level="advanced", description="脚本里写（人物备注、停顿说明）时，开启后圆括号里的说明不会被念出来；普通正文没有这类备注时不用开。"),
                ParameterSchema(key="disable_markdown_filter", label="过滤 Markdown 排版标记", type="toggle", default=False, level="advanced", description="开启后会尽量去掉 **粗体**、链接等常见 Markdown 符号再朗读，避免读出星号等标记。复杂排版未必都能自动清干净，正式生成前仍建议先整理文本。"),
                ParameterSchema(key="latex_parser_mode", label="公式朗读", type="select", default="off", level="advanced", options=[{"label": "关闭", "value": "off"}, {"label": "基础公式朗读", "value": "basic"}, {"label": "增强公式朗读（较慢）", "value": "enhanced"}], description="把 LaTeX 数学写法按公式念出来。普通口播不需要；增强模式更适合复杂公式，但生成会更慢。"),
                ParameterSchema(key="aigc_metadata_enable", label="写入隐藏来源信息", type="toggle", default=False, level="advanced", description="把制作方和传播方等追溯信息写进成品，不会影响正常试听，也不会被朗读。需要平台或内部追溯时再开启。"),
                ParameterSchema(key="content_producer", label="内容制作方", type="text", default="", level="advanced", description="填写制作这段音频的团队、账号或公司名称。它只会写入隐藏来源信息，不会被念出来。"),
                ParameterSchema(key="produce_id", label="制作编号", type="text", default="", level="advanced", description="填写项目编号或内部追踪号。它只用于后续追溯，不会改变声音。"),
                ParameterSchema(key="content_propagator", label="内容传播方", type="text", default="", level="advanced", description="填写准备发布或传播这段音频的账号、团队或平台主体。它只写入隐藏来源信息。"),
                ParameterSchema(key="propagate_id", label="传播编号", type="text", default="", level="advanced", description="填写传播侧的内部编号或账号标识。没有自己的追溯规则时可以留空。"),
                ParameterSchema(key="tone_fidelity", label="更贴近训练音色", type="toggle", default=False, level="advanced", description="更努力保留训练音频原来的说话习惯、情绪和口音。只适合同语种文本；开启后可自由变化的空间会变小。"),
            ],
        ),
        state=EngineState(engine_id="doubao-tts-voiceclone", status=EngineStatus.stopped),
    ),
    "doubao-seed-audio-1.0": EngineDetail(
        manifest=EngineManifest(
            engine_id="doubao-seed-audio-1.0",
            display_name="豆包音频生成 Seed Audio 1.0",
            engine_type="cloud",
            provider="Volcengine / Doubao",
            version="seed-audio-1.0",
            description="根据文字描述、参考声音或参考图片生成最长 120 秒的完整声音场景",
            supported_languages=["zh", "en"],
            capabilities=[
                "cloud_api",
                "audio_generation",
                "reference_audio",
                "reference_image",
                "subtitle",
                "watermark",
                "single_generation",
            ],
            sample_rate=24000,
            default_use_case="声音场景、对白、音乐和环境音的一体化生成",
            privacy_level="cloud_required",
            input_modes=["text", "audio", "image"],
            max_reference_audio=3,
            max_reference_image=1,
            mutually_exclusive_inputs=[["audio", "image"]],
            prompt_reference_syntax="@音频N",
            supported_output_formats=["wav", "mp3", "pcm", "ogg_opus"],
            supported_sample_rates=[8000, 16000, 24000, 32000, 44100, 48000],
            max_prompt_chars=3000,
            max_output_seconds=120,
            parameter_schema=[
                ParameterSchema(
                    key="format",
                    label="输出格式",
                    type="select",
                    default="wav",
                    options=[{"label": value, "value": value} for value in ["wav", "mp3", "pcm", "ogg_opus"]],
                    description="选择交付文件的格式。WAV 兼容后期制作；MP3 体积小、便于分享；OGG Opus 是较小体积的压缩格式；PCM 是没有文件头的原始音频，常规播放器和网页通常不能直接试听。",
                ),
                ParameterSchema(
                    key="sample_rate",
                    label="采样率",
                    type="select",
                    default=24000,
                    options=[{"label": f"{value} Hz", "value": value} for value in [8000, 16000, 24000, 32000, 44100, 48000]],
                    description="决定输出文件保留多少声音细节。数值高通常更清晰、文件更大；24 kHz 适合一般试听，48 kHz 更适合视频后期。",
                    level="advanced",
                ),
                ParameterSchema(key="enable_subtitle", label="返回字幕时间戳", type="toggle", default=False, level="advanced", description="生成时一并返回每段文字的大致出现时间。后面要做字幕、口型或画面对齐时再开启；只想试听时不用开。"),
                ParameterSchema(key="speech_rate", label="整体语速", type="slider", default=0, min=-50, max=100, step=1, description="主要调整人声的说话快慢。0 保持模型原来的节奏；往右会更快，往左会更慢。它不保证整段音乐和音效也按相同比例变速，复杂对白建议先小幅调整。"),
                ParameterSchema(key="loudness_rate", label="整体音量", type="slider", default=0, min=-50, max=100, step=1, level="advanced", description="整体提高或降低成品音量。0 保持原样；往右更响，往左更轻。它不会修复爆音或底噪，混音前可先保持默认。"),
                ParameterSchema(key="pitch_rate", label="整体音调", type="slider", default=0, min=-12, max=12, step=1, level="advanced", description="整体抬高或压低声音的高低。0 不变；调高更尖亮，调低更厚沉。改得太多会显得不像自然人声。"),
                ParameterSchema(key="aigc_watermark", label="显式音频水印", type="toggle", default=False, level="advanced", description="会在音频结尾加入一小段可识别的 AI 生成节奏标记，便于平台或后续流程识别来源。需要合规标记时开启；纯内部试听或不想改变结尾听感时可关闭。"),
                ParameterSchema(key="aigc_metadata_enable", label="隐式来源信息", type="toggle", default=False, level="advanced", description="把制作与传播来源信息写进音频的隐藏元数据，不会改变正常试听效果。只有你会填写下面的来源信息时才需要开启。"),
                ParameterSchema(key="content_producer", label="内容制作方", type="text", default="", level="advanced", description="填写制作这段音频的团队、账号或公司名称。它会作为隐藏来源信息的一部分，不会被朗读出来。"),
                ParameterSchema(key="produce_id", label="制作编号", type="text", default="", level="advanced", description="填写你自己的制作编号，例如项目编号或内部追踪号。用于后续追溯，不会影响声音内容。"),
                ParameterSchema(key="content_propagator", label="内容传播方", type="text", default="", level="advanced", description="填写准备发布或传播这段音频的账号、团队或平台主体。它只写入隐藏来源信息，不会被朗读。"),
                ParameterSchema(key="propagate_id", label="传播编号", type="text", default="", level="advanced", description="填写传播侧的内部编号或账号标识。没有自己的追溯规则时可留空，不会影响生成结果。"),
            ],
        ),
        state=EngineState(engine_id="doubao-seed-audio-1.0", status=EngineStatus.stopped),
    ),
    "qwen3-asr-mlx": EngineDetail(
        manifest=EngineManifest(
            engine_id="qwen3-asr-mlx",
            display_name="Qwen3-ASR MLX",
            provider="Qwen + MLX Community",
            version="1.7B 8-bit",
            description="本地 Apple Silicon 语音识别，Qwen3-ASR 1.7B MLX 量化推理，超越 Whisper-large-v3",
            supported_languages=["auto", "zh", "en"],
            capabilities=["local_inference", "speech_recognition", "transcription", "language_identification"],
            default_use_case="离线音频转写与云端 ASR 备选",
            parameter_schema=[
                ParameterSchema(key="language", label="识别语言", type="select", default="auto", options=[{"label": x, "value": x} for x in ["auto", "zh", "en"]], description="选择识别语言，auto 自动检测")
            ],
        ),
        state=EngineState(engine_id="qwen3-asr-mlx", status=EngineStatus.stopped),
    ),
    "faster-whisper-turbo": EngineDetail(
        manifest=EngineManifest(
            engine_id="faster-whisper-turbo",
            display_name="Faster Whisper Turbo",
            provider="SYSTRAN faster-whisper + OpenAI Whisper",
            version="large-v3-turbo / CTranslate2",
            description="本地 faster-whisper 英文优先转写，面向视频本土化初稿字幕；原始模型 openai/whisper-large-v3-turbo，运行时使用 CTranslate2 转换模型。",
            supported_languages=["auto", "en"],
            capabilities=["local_inference", "speech_recognition", "transcription", "language_identification", "vad"],
            default_use_case="英文视频快速转写、时间轴字幕初稿和人工校对入口",
            privacy_level="local_only",
            parameter_schema=[
                ParameterSchema(key="language", label="识别语言", type="select", default="en", options=[{"label": x, "value": x} for x in ["en", "auto"]], description="视频本土化默认英文识别；auto 用于少量混语素材。")
            ],
        ),
        state=EngineState(engine_id="faster-whisper-turbo", status=EngineStatus.stopped),
    ),
}
